import { Exercise, ExerciseType, Difficulty, NoteConfig, ExerciseCategory, Hand } from './types';
import type { DynamicLevel } from './utils/dynamics';

export const PIANO_KEYS_OCTAVE: NoteConfig[] = [
  { name: 'C', isBlack: false },
  { name: 'C#', isBlack: true },
  { name: 'D', isBlack: false },
  { name: 'D#', isBlack: true },
  { name: 'E', isBlack: false },
  { name: 'F', isBlack: false },
  { name: 'F#', isBlack: true },
  { name: 'G', isBlack: false },
  { name: 'G#', isBlack: true },
  { name: 'A', isBlack: false },
  { name: 'A#', isBlack: true },
  { name: 'B', isBlack: false },
];

export const DAILY_DOZEN_IDS = [
  'dd-1-b-major-rh',
  'dd-2-b-major-lh',
  'dd-3-thumb-pivot',
  'dd-4-legato-connection',
  'dd-5-trill-3-4',
  'dd-6-arpeggio-rh',
  'dd-7-chromatic-rh',
  'dd-8-wrist-staccato',
  'dd-9-solid-chords',
  'dd-10-dynamics',
  'dd-11-rubato-scale',
  'dd-12-cantabile',
];

export const CHOPIN_EXERCISES: Exercise[] = [
  // ============================================================
  // DAILY DOZEN — The daily warm-up and foundation routine
  // Ordered by Chopin's pedagogy: natural position first,
  // then technique, then musicality
  // ============================================================

  {
    id: 'dd-1-b-major-rh',
    title: '1. B Major Five-Finger (RH)',
    description: 'Chopin always began here. The long fingers (2,3,4) rest on the black keys (C#, D#, F#), thumb and pinky find the white keys (B, E). This is the hand\'s natural shape on the keyboard.',
    category: ExerciseCategory.Technical,
    type: ExerciseType.Scale,
    difficulty: Difficulty.Beginner,
    key: 'B Major',
    hand: 'right' as Hand,
    notes: ['B3', 'C#4', 'D#4', 'E4', 'F#4', 'E4', 'D#4', 'C#4', 'B3'],
    fingerings: [
      { note: 'B3', finger: 1, hand: 'right' },
      { note: 'C#4', finger: 2, hand: 'right' },
      { note: 'D#4', finger: 3, hand: 'right' },
      { note: 'E4', finger: 4, hand: 'right' },
      { note: 'F#4', finger: 5, hand: 'right' },
    ],
    tips: [
      'Mold the hand over the keys like a dome. Knuckles slightly raised.',
      'Do not press down; sink into each key with arm weight.',
      'Each finger lifts only after the next key is fully down (legato).',
      'Even here, make it sing. A five-finger pattern played beautifully is worth more than a sonata played mechanically.',
      'Variation: play it forte, then pianissimo. The hand shape stays identical; only the key speed changes.',
    ],
  },
  {
    id: 'dd-2-b-major-lh',
    title: '2. B Major Five-Finger (LH)',
    description: 'Mirror the right hand. The left hand finds the same natural dome over B Major, with pinky on B and thumb on F#.',
    category: ExerciseCategory.Technical,
    type: ExerciseType.Scale,
    difficulty: Difficulty.Beginner,
    key: 'B Major',
    hand: 'left' as Hand,
    notes: ['F#4', 'E4', 'D#4', 'C#4', 'B3', 'C#4', 'D#4', 'E4', 'F#4'],
    fingerings: [
      { note: 'F#4', finger: 1, hand: 'left' },
      { note: 'E4', finger: 2, hand: 'left' },
      { note: 'D#4', finger: 3, hand: 'left' },
      { note: 'C#4', finger: 4, hand: 'left' },
      { note: 'B3', finger: 5, hand: 'left' },
    ],
    tips: [
      'Same dome shape, same relaxation. Mirror, don\'t reinvent.',
      'The thumb (1) starts on F# — let it rest on the black key naturally.',
      'Variation: play right hand, then left hand, then alternate one note at a time between hands. The handoff should be invisible.',
    ],
  },
  {
    id: 'dd-3-thumb-pivot',
    title: '3. Thumb Under Pass',
    description: 'The thumb is the axis of the hand. Practice passing it under fingers 2 and 3 smoothly, keeping the wrist level — no elbow jerking.',
    category: ExerciseCategory.Technical,
    type: ExerciseType.Drill,
    difficulty: Difficulty.Beginner,
    key: 'C Major',
    hand: 'right' as Hand,
    notes: ['C4', 'D4', 'E4', 'F4', 'G4', 'A4', 'B4', 'C5'],
    fingerings: [
      { note: 'C4', finger: 1, hand: 'right' },
      { note: 'D4', finger: 2, hand: 'right' },
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'F4', finger: 1, hand: 'right' },
      { note: 'G4', finger: 2, hand: 'right' },
      { note: 'A4', finger: 3, hand: 'right' },
      { note: 'B4', finger: 4, hand: 'right' },
      { note: 'C5', finger: 5, hand: 'right' },
    ],
    tips: [
      'The thumb moves laterally under the hand, like a crab.',
      'The wrist stays level. If it dips when the thumb passes, slow down.',
      'This is the foundation of every scale and arpeggio.',
      'In real music: every scale passage, every arpeggio, every Chopin run depends on this one motion. Master it and the repertoire opens up.',
      'Variation: try ascending then descending. The descent is harder — the thumb must lead in the opposite direction.',
    ],
  },
  {
    id: 'dd-4-legato-connection',
    title: '4. Legato Connection',
    description: 'True legato means one key releases at the exact moment the next goes down. No gap, no overlap. Chopin called this "the singing touch."',
    category: ExerciseCategory.Musicality,
    type: ExerciseType.Drill,
    difficulty: Difficulty.Beginner,
    key: 'E Major',
    hand: 'right' as Hand,
    notes: ['E4', 'F#4', 'G#4', 'A4', 'B4', 'A4', 'G#4', 'F#4', 'E4'],
    fingerings: [
      { note: 'E4', finger: 1, hand: 'right' },
      { note: 'F#4', finger: 2, hand: 'right' },
      { note: 'G#4', finger: 3, hand: 'right' },
      { note: 'A4', finger: 4, hand: 'right' },
      { note: 'B4', finger: 5, hand: 'right' },
    ],
    tips: [
      'Listen for any silence between notes. There should be none.',
      'Listen for any "smudge" where two notes sound together. There should be none.',
      'Play at half the tempo you think is right.',
      'Imagine each note is a syllable in a sung phrase. The breath between syllables is seamless, but each syllable has its own weight.',
      'Variation: try emphasizing a different note each time through. How does the phrase\'s meaning change?',
    ],
  },
  {
    id: 'dd-5-trill-3-4',
    title: '5. Weak Finger Independence (3-4)',
    description: 'Fingers 3 and 4 share a tendon. Chopin knew they would never be equally strong, but they can be equally controlled. Slow, even alternation.',
    category: ExerciseCategory.Technical,
    type: ExerciseType.Drill,
    difficulty: Difficulty.Intermediate,
    key: 'C Major',
    hand: 'right' as Hand,
    notes: ['E4', 'F4', 'E4', 'F4', 'E4', 'F4', 'E4', 'F4'],
    fingerings: [
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'F4', finger: 4, hand: 'right' },
    ],
    tips: [
      'Evenness is the only goal. Not speed.',
      'Keep fingers 1, 2, and 5 completely relaxed — they should feel dead.',
      'If tension creeps in, stop immediately. Shake out your hand.',
      'In real music: trills between 3 and 4 appear throughout Chopin\'s Nocturnes. This drill is their foundation.',
      'Variation: after 8 even repetitions, try accenting every other note. Then every third. This develops rhythmic independence.',
    ],
  },
  {
    id: 'dd-6-arpeggio-rh',
    title: '6. E Major Arpeggio',
    description: 'Expanding the hand across wider intervals. The wrist leads the hand laterally — fingers follow, they don\'t reach.',
    category: ExerciseCategory.Technical,
    type: ExerciseType.Arpeggio,
    difficulty: Difficulty.Beginner,
    key: 'E Major',
    hand: 'right' as Hand,
    notes: ['E3', 'G#3', 'B3', 'E4', 'B3', 'G#3', 'E3'],
    fingerings: [
      { note: 'E3', finger: 1, hand: 'right' },
      { note: 'G#3', finger: 2, hand: 'right' },
      { note: 'B3', finger: 3, hand: 'right' },
      { note: 'E4', finger: 5, hand: 'right' },
    ],
    tips: [
      'Move the wrist laterally to help the fingers reach — don\'t stretch.',
      'The elbow floats slightly outward on the ascent.',
      'Shape the arpeggio like a vocal phrase: grow louder ascending, softer descending. Even a technical pattern can sing.',
      'In real music: arpeggiated chords open Chopin\'s Ballade No. 1 and define his Nocturnes. This motion is everywhere.',
    ],
  },
  {
    id: 'dd-7-chromatic-rh',
    title: '7. Chromatic Scale',
    description: 'Half-step movement develops finger independence and keeps the hand close to the keys. Thumb on white keys, finger 3 on black keys.',
    category: ExerciseCategory.Technical,
    type: ExerciseType.Scale,
    difficulty: Difficulty.Intermediate,
    key: 'Chromatic',
    hand: 'right' as Hand,
    notes: ['C4', 'C#4', 'D4', 'D#4', 'E4', 'F4', 'F#4', 'G4'],
    fingerings: [
      { note: 'C4', finger: 1, hand: 'right' },
      { note: 'C#4', finger: 3, hand: 'right' },
      { note: 'D4', finger: 1, hand: 'right' },
      { note: 'D#4', finger: 3, hand: 'right' },
      { note: 'E4', finger: 1, hand: 'right' },
      { note: 'F4', finger: 1, hand: 'right' },
      { note: 'F#4', finger: 3, hand: 'right' },
      { note: 'G4', finger: 1, hand: 'right' },
    ],
    tips: [
      'Stay close to the keys. No finger should lift more than a centimeter.',
      'The thumb slides laterally, never lifts.',
      'Variation: play it as a whisper (pp), then as a conversation (mf). The finger technique stays identical; only the intention changes.',
      'In real music: chromatic passages add color and tension. They are the spice in Chopin\'s harmonic palette.',
    ],
  },
  {
    id: 'dd-8-wrist-staccato',
    title: '8. Wrist Staccato',
    description: 'Short, bouncy notes produced by wrist motion alone. The forearm stays still. Think of waving goodbye — only the wrist moves.',
    category: ExerciseCategory.Technical,
    type: ExerciseType.Drill,
    difficulty: Difficulty.Intermediate,
    key: 'C Major',
    hand: 'right' as Hand,
    notes: ['C4', 'E4', 'G4', 'E4', 'C4', 'E4', 'G4', 'E4'],
    fingerings: [
      { note: 'C4', finger: 1, hand: 'right' },
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'G4', finger: 5, hand: 'right' },
    ],
    tips: [
      'The wrist acts as a spring — down and immediately release.',
      'The sound should be crisp and light, never harsh.',
      'If your forearm tenses, you\'re using the wrong muscle group.',
      'Once comfortable: play the same pattern legato, then staccato, then legato again. Hear how articulation changes the character of identical notes.',
      'In real music: staccato passages in Chopin\'s Scherzos are electric. This wrist motion is the engine behind them.',
    ],
  },
  {
    id: 'dd-9-solid-chords',
    title: '9. Chord Weight Transfer',
    description: 'Play a full triad and let the weight of your arm settle into the keys. Feel the bottom of the keybed. Then release all tension immediately.',
    category: ExerciseCategory.Musicality,
    type: ExerciseType.Chord,
    difficulty: Difficulty.Beginner,
    key: 'C Major',
    hand: 'both' as Hand,
    notes: ['C4', 'E4', 'G4'],
    fingerings: [
      { note: 'C4', finger: 1, hand: 'right' },
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'G4', finger: 5, hand: 'right' },
    ],
    tips: [
      'All three notes must sound at the exact same instant.',
      'Drop into the chord, then immediately relax. The key holds the note, not your muscles.',
      'Try C major, then F major (F-A-C), then G major (G-B-D).',
      'Each chord has its own emotion. C major is home. F major is warmth. G major is anticipation. Listen to the difference.',
      'Variation: sustain the chord for four beats, then play it staccato. Both should sound equally full and resonant.',
    ],
  },
  {
    id: 'dd-10-dynamics',
    title: '10. pp to ff and Back',
    description: 'Play the same five notes getting gradually louder, then gradually softer. Volume is controlled by the speed of key descent, not by force.',
    category: ExerciseCategory.Musicality,
    type: ExerciseType.Drill,
    difficulty: Difficulty.Beginner,
    key: 'C Major',
    hand: 'right' as Hand,
    notes: ['C4', 'D4', 'E4', 'F4', 'G4', 'F4', 'E4', 'D4', 'C4'],
    fingerings: [
      { note: 'C4', finger: 1, hand: 'right' },
      { note: 'D4', finger: 2, hand: 'right' },
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'F4', finger: 4, hand: 'right' },
      { note: 'G4', finger: 5, hand: 'right' },
    ],
    targetDynamic: ['pp', 'p', 'mp', 'mf', 'ff', 'mf', 'mp', 'p', 'pp'] as DynamicLevel[],
    tips: [
      'Start as quiet as physically possible. Barely touch the key.',
      'Peak volume at G4, then descend back to silence.',
      'Faster key descent = louder. Not more arm weight.',
      'Think of dynamics as the emotional temperature of a phrase, not just volume. Piano is intimate. Forte is urgent.',
      'Variation: try the same pattern starting from ff and descending to pp. The emotional arc reverses completely.',
    ],
  },
  {
    id: 'dd-11-rubato-scale',
    title: '11. Breathing Scale',
    description: 'A scale is a musical phrase, not a finger exercise. Breathe at the top and bottom. Slight acceleration in the middle, slight deceleration at the turns.',
    category: ExerciseCategory.Musicality,
    type: ExerciseType.Scale,
    difficulty: Difficulty.Intermediate,
    key: 'A Minor',
    hand: 'right' as Hand,
    notes: ['A3', 'B3', 'C4', 'D4', 'E4', 'F4', 'G#4', 'A4'],
    fingerings: [
      { note: 'A3', finger: 1, hand: 'right' },
      { note: 'B3', finger: 2, hand: 'right' },
      { note: 'C4', finger: 3, hand: 'right' },
      { note: 'D4', finger: 1, hand: 'right' },
      { note: 'E4', finger: 2, hand: 'right' },
      { note: 'F4', finger: 3, hand: 'right' },
      { note: 'G#4', finger: 4, hand: 'right' },
      { note: 'A4', finger: 5, hand: 'right' },
    ],
    tips: [
      'Think of each scale as a spoken sentence. It has shape.',
      'The pulse stays steady underneath, but the surface breathes.',
      'Chopin: "The left hand is the conductor. The right hand does what it wants."',
      'This scale is telling a story. The ascent asks a question; the top note is the climax; the descent is the resolution.',
      'Variation: play with eyes closed. Let your ear guide the phrasing, not your eyes. Trust the hand you have trained.',
    ],
  },
  {
    id: 'dd-12-cantabile',
    title: '12. Cantabile Melody',
    description: 'End each session with beauty. Play this simple melody as if you are singing it. Every note should have meaning. This is why we practice.',
    category: ExerciseCategory.Musicality,
    type: ExerciseType.Concept,
    difficulty: Difficulty.Beginner,
    key: 'C Major',
    hand: 'right' as Hand,
    notes: ['E4', 'F4', 'G4', 'A4', 'G4', 'F4', 'E4', 'D4', 'C4'],
    fingerings: [
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'F4', finger: 4, hand: 'right' },
      { note: 'G4', finger: 5, hand: 'right' },
      { note: 'A4', finger: 1, hand: 'right' },
      { note: 'G4', finger: 5, hand: 'right' },
      { note: 'F4', finger: 4, hand: 'right' },
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'D4', finger: 2, hand: 'right' },
      { note: 'C4', finger: 1, hand: 'right' },
    ],
    tips: [
      'Listen to the decay of each note before playing the next.',
      'Shape the phrase: grow toward A4, then gently descend.',
      'If it doesn\'t sound like singing, slow down until it does.',
      'Variation: play it once as a question (slight pause before the last note). Then play it as an answer (decisive, no hesitation). Same notes, different meaning.',
      'This is why we practice technique: so that moments like this, when the music must simply sing, cost us nothing.',
    ],
  },

  // ============================================================
  // SUPPLEMENTARY EXERCISES — Available in the Curriculum
  // ============================================================

  // --- Technical ---
  {
    id: 'c-major-scale-rh',
    title: 'C Major Scale (RH)',
    description: 'The most important scale to master, but counterintuitively the hardest. No black keys means no natural pivot points for the thumb — every transition must be deliberate.',
    category: ExerciseCategory.Technical,
    type: ExerciseType.Scale,
    difficulty: Difficulty.Intermediate,
    key: 'C Major',
    hand: 'right' as Hand,
    notes: ['C4', 'D4', 'E4', 'F4', 'G4', 'A4', 'B4', 'C5'],
    fingerings: [
      { note: 'C4', finger: 1, hand: 'right' },
      { note: 'D4', finger: 2, hand: 'right' },
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'F4', finger: 1, hand: 'right' },
      { note: 'G4', finger: 2, hand: 'right' },
      { note: 'A4', finger: 3, hand: 'right' },
      { note: 'B4', finger: 4, hand: 'right' },
      { note: 'C5', finger: 5, hand: 'right' },
    ],
    tips: [
      'This was NOT Chopin\'s first scale for a reason. B Major teaches the hand shape; C Major tests it.',
      'Master B Major first, then bring that relaxation to C Major.',
      'Even a C major scale should sound musical. Shape it: start soft, swell in the middle, land gently at the top.',
    ],
  },
  {
    id: 'db-major-scale-rh',
    title: 'Db Major Scale (RH)',
    description: 'Chopin\'s second scale after B Major. Five black keys keep the hand in its natural curved position.',
    category: ExerciseCategory.Technical,
    type: ExerciseType.Scale,
    difficulty: Difficulty.Intermediate,
    key: 'Db Major',
    hand: 'right' as Hand,
    notes: ['Db4', 'Eb4', 'F4', 'Gb4', 'Ab4', 'Bb4', 'C5', 'Db5'],
    fingerings: [
      { note: 'Db4', finger: 2, hand: 'right' },
      { note: 'Eb4', finger: 3, hand: 'right' },
      { note: 'F4', finger: 1, hand: 'right' },
      { note: 'Gb4', finger: 2, hand: 'right' },
      { note: 'Ab4', finger: 3, hand: 'right' },
      { note: 'Bb4', finger: 4, hand: 'right' },
      { note: 'C5', finger: 1, hand: 'right' },
      { note: 'Db5', finger: 2, hand: 'right' },
    ],
    tips: [
      'Thumb plays only white keys (F and C). The hand stays high on the keyboard.',
      'This feels more natural than C Major — that\'s Chopin\'s whole point.',
      'Variation: play it as if you are telling someone a secret (pp, intimate) versus announcing something (f, projected).',
    ],
  },
  {
    id: 'arpeggio-lh',
    title: 'E Major Arpeggio (LH)',
    description: 'Left hand arpeggio descending. The wrist guides the hand downward smoothly.',
    category: ExerciseCategory.Technical,
    type: ExerciseType.Arpeggio,
    difficulty: Difficulty.Beginner,
    key: 'E Major',
    hand: 'left' as Hand,
    notes: ['E4', 'B3', 'G#3', 'E3', 'G#3', 'B3', 'E4'],
    fingerings: [
      { note: 'E4', finger: 1, hand: 'left' },
      { note: 'B3', finger: 2, hand: 'left' },
      { note: 'G#3', finger: 3, hand: 'left' },
      { note: 'E3', finger: 5, hand: 'left' },
    ],
    tips: [
      'Descend smoothly. The wrist guides the hand downward.',
      'On the ascent, let the elbow float outward naturally.',
    ],
  },
  {
    id: 'chromatic-lh',
    title: 'Chromatic Scale (LH)',
    description: 'Left hand chromatic descent. Mirror the right hand technique.',
    category: ExerciseCategory.Technical,
    type: ExerciseType.Scale,
    difficulty: Difficulty.Intermediate,
    key: 'Chromatic',
    hand: 'left' as Hand,
    notes: ['G4', 'F#4', 'F4', 'E4', 'D#4', 'D4', 'C#4', 'C4'],
    fingerings: [
      { note: 'G4', finger: 1, hand: 'left' },
      { note: 'F#4', finger: 3, hand: 'left' },
      { note: 'F4', finger: 1, hand: 'left' },
      { note: 'E4', finger: 1, hand: 'left' },
      { note: 'D#4', finger: 3, hand: 'left' },
      { note: 'D4', finger: 1, hand: 'left' },
      { note: 'C#4', finger: 3, hand: 'left' },
      { note: 'C4', finger: 1, hand: 'left' },
    ],
    tips: [
      'Mirror the right hand pattern. Stay close to the keys.',
    ],
  },
  {
    id: 'double-thirds',
    title: 'Double Thirds',
    description: 'Play pairs of notes a third apart in sequence. Develops coordination between finger pairs and is essential for advanced repertoire.',
    category: ExerciseCategory.Technical,
    type: ExerciseType.Drill,
    difficulty: Difficulty.Advanced,
    key: 'C Major',
    hand: 'right' as Hand,
    notes: ['C4', 'E4', 'D4', 'F4', 'E4', 'G4', 'F4', 'A4'],
    fingerings: [
      { note: 'C4', finger: 1, hand: 'right' },
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'D4', finger: 2, hand: 'right' },
      { note: 'F4', finger: 4, hand: 'right' },
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'G4', finger: 5, hand: 'right' },
    ],
    tips: [
      'Both notes in each pair must sound at the exact same instant.',
      'Keep the wrist flexible. It rises and falls with the phrase.',
      'In real music: double thirds appear in Chopin\'s Etude Op. 25 No. 6. This is the door to that world.',
    ],
  },
  {
    id: 'trill-4-5',
    title: 'Weak Finger Independence (4-5)',
    description: 'The weakest pair. Slow, controlled alternation between ring finger and pinky builds the independence needed for polyphonic playing.',
    category: ExerciseCategory.Technical,
    type: ExerciseType.Drill,
    difficulty: Difficulty.Advanced,
    key: 'C Major',
    hand: 'right' as Hand,
    notes: ['G4', 'A4', 'G4', 'A4', 'G4', 'A4', 'G4', 'A4'],
    fingerings: [
      { note: 'G4', finger: 4, hand: 'right' },
      { note: 'A4', finger: 5, hand: 'right' },
    ],
    tips: [
      'This will feel difficult. That is the point.',
      'Evenness matters more than speed. Always.',
      'Rest every 30 seconds. This pair fatigues fast.',
      'Chopin never tried to make all fingers equal. He wanted each finger to be independently expressive. Finger 4 is tender; finger 5 is bright. Train them, don\'t erase them.',
    ],
  },

  // --- Musicality ---
  {
    id: 'chord-progressions',
    title: 'I-IV-V-I Progression',
    description: 'The harmonic foundation of Western music. Hear how C major (home) moves to F major (away) to G major (tension) and resolves back to C.',
    category: ExerciseCategory.Musicality,
    type: ExerciseType.Chord,
    difficulty: Difficulty.Beginner,
    key: 'C Major',
    hand: 'right' as Hand,
    notes: ['C4', 'E4', 'G4', 'F4', 'A4', 'C5', 'G4', 'B4', 'D5', 'C4', 'E4', 'G4'],
    fingerings: [
      { note: 'C4', finger: 1, hand: 'right' },
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'G4', finger: 5, hand: 'right' },
    ],
    tips: [
      'Listen to the emotional journey: rest, departure, tension, resolution.',
      'This is the skeleton of most music you have ever heard.',
      'This progression is a sentence. I (C) is the subject. IV (F) is the verb. V (G) is the question mark. I (C) again is the period.',
    ],
  },
  {
    id: 'lh-accompaniment',
    title: 'Left Hand Accompaniment Pattern',
    description: 'A basic Alberti bass pattern — broken chord accompaniment that the left hand plays while the right hand sings a melody.',
    category: ExerciseCategory.Musicality,
    type: ExerciseType.Drill,
    difficulty: Difficulty.Intermediate,
    key: 'C Major',
    hand: 'left' as Hand,
    notes: ['C3', 'G3', 'E3', 'G3', 'C3', 'G3', 'E3', 'G3'],
    fingerings: [
      { note: 'C3', finger: 5, hand: 'left' },
      { note: 'G3', finger: 1, hand: 'left' },
      { note: 'E3', finger: 3, hand: 'left' },
    ],
    tips: [
      'Keep this soft and even. The left hand accompanies, it doesn\'t compete.',
      'The pattern should feel like breathing — completely automatic.',
      'In real music: this pattern underpins Mozart sonatas, Chopin Nocturnes, and pop ballads. It is the heartbeat beneath the melody.',
    ],
  },

  // --- Practice Habits ---
  {
    id: 'slow-practice',
    title: 'Slow Practice Discipline',
    description: 'Play any five-note pattern at half the speed you think is right. After each note, check: is my shoulder dropped? Is my wrist loose? Am I breathing?',
    category: ExerciseCategory.Habits,
    type: ExerciseType.Drill,
    difficulty: Difficulty.Beginner,
    key: 'C Major',
    hand: 'right' as Hand,
    notes: ['C4', 'D4', 'E4', 'F4', 'G4'],
    fingerings: [
      { note: 'C4', finger: 1, hand: 'right' },
      { note: 'D4', finger: 2, hand: 'right' },
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'F4', finger: 4, hand: 'right' },
      { note: 'G4', finger: 5, hand: 'right' },
    ],
    tips: [
      'Play a note, then wiggle your wrist to verify zero tension.',
      'Only move to the next note when the hand is completely relaxed.',
      'Chopin: "Whoever plays too fast has never truly played slowly."',
      'Why this matters: speed is a byproduct of relaxed accuracy. You cannot add speed to tense playing; you can only add speed to relaxed playing.',
    ],
  },
  {
    id: 'relaxation-check',
    title: 'Tension Reset',
    description: 'Drop both arms to your sides like dead weight. Roll your shoulders back. Shake out your wrists. Then place your hands on the keys without pressing anything. This is your baseline.',
    category: ExerciseCategory.Habits,
    type: ExerciseType.Mental,
    difficulty: Difficulty.Beginner,
    key: 'N/A',
    hand: 'both' as Hand,
    notes: [],
    fingerings: [],
    tips: [
      'Do this whenever you notice tension building during practice.',
      'Your shoulders should never be raised while playing.',
      'The hand on the keys should feel like it\'s resting on a table — no effort.',
    ],
  },

  // --- Theory & Ear ---
  {
    id: 'intervals',
    title: 'Hearing Intervals',
    description: 'Play C then E: that\'s a major third (bright, happy). Play C then G: that\'s a perfect fifth (open, stable). Play C then Eb: minor third (darker, more complex).',
    category: ExerciseCategory.Theory,
    type: ExerciseType.Drill,
    difficulty: Difficulty.Beginner,
    key: 'C Major',
    hand: 'right' as Hand,
    notes: ['C4', 'E4', 'C4', 'G4', 'C4', 'D#4'],
    fingerings: [],
    tips: [
      'After playing each pair, sing both notes. Can you match the pitch?',
      'The fifth (C-G) sounds "hollow." The third (C-E) sounds "warm."',
      'Minor third (C-Eb) sounds like the beginning of something sad.',
      'Intervals are the vowels of music. Melodies are just intervals strung together. Learn to hear them and you can hear anything.',
    ],
  },

  // --- Hand Coordination ---
  {
    id: 'ht-alternating',
    title: 'Alternating Hands',
    description: 'The simplest hands-together exercise. Each hand takes turns playing a note from a C major triad. Focus on smooth transitions between hands — no pause, no rushing.',
    category: ExerciseCategory.HandCoordination,
    type: ExerciseType.Drill,
    difficulty: Difficulty.Beginner,
    key: 'C Major',
    hand: 'both' as Hand,
    notes: ['C3', 'C4', 'E3', 'E4', 'G3', 'G4', 'E3', 'E4', 'C3', 'C4'],
    fingerings: [
      { note: 'C3', finger: 5, hand: 'left' },
      { note: 'E3', finger: 3, hand: 'left' },
      { note: 'G3', finger: 1, hand: 'left' },
      { note: 'C4', finger: 1, hand: 'right' },
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'G4', finger: 5, hand: 'right' },
    ],
    tips: [
      'Low notes (C3, E3, G3) are left hand. High notes (C4, E4, G4) are right hand.',
      'The handoff between hands should be seamless — no gap in sound.',
      'Keep both hands hovering over their position even when not playing.',
    ],
  },
  {
    id: 'ht-melody-bass',
    title: 'Melody Over Bass',
    description: 'Right hand plays a simple melody while left hand provides bass notes. This is the foundation of all piano music: one hand sings, one hand supports.',
    category: ExerciseCategory.HandCoordination,
    type: ExerciseType.Drill,
    difficulty: Difficulty.Beginner,
    key: 'C Major',
    hand: 'both' as Hand,
    notes: ['C3', 'E4', 'C3', 'F4', 'C3', 'G4', 'C3', 'A4', 'G3', 'G4', 'G3', 'F4', 'G3', 'E4', 'C3', 'C4'],
    fingerings: [
      { note: 'C3', finger: 5, hand: 'left' },
      { note: 'G3', finger: 1, hand: 'left' },
      { note: 'C4', finger: 1, hand: 'right' },
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'F4', finger: 4, hand: 'right' },
      { note: 'G4', finger: 5, hand: 'right' },
      { note: 'A4', finger: 5, hand: 'right' },
    ],
    tips: [
      'Left hand plays softly — it supports, it does not compete.',
      'Right hand melody should sing above the bass.',
      'Chopin: "The left hand is the conductor. The right hand does what it wants."',
      'The right hand speaks the words. The left hand is the tone of voice. Together they make meaning.',
    ],
  },
  {
    id: 'ht-contrary-motion',
    title: 'Contrary Motion',
    description: 'Both hands start on E and move in opposite directions — right hand ascends, left hand descends. This teaches independent hand movement, the core skill of piano.',
    category: ExerciseCategory.HandCoordination,
    type: ExerciseType.Drill,
    difficulty: Difficulty.Intermediate,
    key: 'C Major',
    hand: 'both' as Hand,
    notes: ['E3', 'E4', 'D3', 'F4', 'C3', 'G4', 'D3', 'F4', 'E3', 'E4'],
    fingerings: [
      { note: 'E3', finger: 3, hand: 'left' },
      { note: 'D3', finger: 4, hand: 'left' },
      { note: 'C3', finger: 5, hand: 'left' },
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'F4', finger: 4, hand: 'right' },
      { note: 'G4', finger: 5, hand: 'right' },
    ],
    tips: [
      'Play each pair together in your mind, even though you play them one at a time here.',
      'The hands mirror each other — as one opens, the other closes.',
      'Once comfortable, try playing both notes simultaneously at the piano.',
      'This is a conversation between two voices. One asks a question (ascending); the other answers (descending).',
    ],
  },

  // --- Additional Scales ---
  {
    id: 'g-major-scale-rh',
    title: 'G Major Scale (RH)',
    description: 'One sharp (F#) gives the thumb a clear pivot point. A comfortable scale that bridges B Major and C Major.',
    category: ExerciseCategory.Technical,
    type: ExerciseType.Scale,
    difficulty: Difficulty.Beginner,
    key: 'G Major',
    hand: 'right' as Hand,
    notes: ['G3', 'A3', 'B3', 'C4', 'D4', 'E4', 'F#4', 'G4'],
    fingerings: [
      { note: 'G3', finger: 1, hand: 'right' },
      { note: 'A3', finger: 2, hand: 'right' },
      { note: 'B3', finger: 3, hand: 'right' },
      { note: 'C4', finger: 1, hand: 'right' },
      { note: 'D4', finger: 2, hand: 'right' },
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'F#4', finger: 4, hand: 'right' },
      { note: 'G4', finger: 5, hand: 'right' },
    ],
    tips: [
      'The F# gives finger 4 a black key — use it as a landmark.',
      'Thumb passes under after B3. Keep the wrist level.',
    ],
  },
  {
    id: 'd-major-scale-rh',
    title: 'D Major Scale (RH)',
    description: 'Two sharps (F# and C#). The hand alternates between black and white keys at regular intervals, developing spatial awareness.',
    category: ExerciseCategory.Technical,
    type: ExerciseType.Scale,
    difficulty: Difficulty.Beginner,
    key: 'D Major',
    hand: 'right' as Hand,
    notes: ['D4', 'E4', 'F#4', 'G4', 'A4', 'B4', 'C#5', 'D5'],
    fingerings: [
      { note: 'D4', finger: 1, hand: 'right' },
      { note: 'E4', finger: 2, hand: 'right' },
      { note: 'F#4', finger: 3, hand: 'right' },
      { note: 'G4', finger: 1, hand: 'right' },
      { note: 'A4', finger: 2, hand: 'right' },
      { note: 'B4', finger: 3, hand: 'right' },
      { note: 'C#5', finger: 4, hand: 'right' },
      { note: 'D5', finger: 5, hand: 'right' },
    ],
    tips: [
      'Two black keys (F# and C#) act as guideposts for the hand.',
      'Thumb passes under after F#4. The transition should be inaudible.',
    ],
  },
  {
    id: 'f-major-scale-rh',
    title: 'F Major Scale (RH)',
    description: 'One flat (Bb). The only major scale where finger 4 plays the single black key. Develops awareness of the thumb-under pass at a different position.',
    category: ExerciseCategory.Technical,
    type: ExerciseType.Scale,
    difficulty: Difficulty.Intermediate,
    key: 'F Major',
    hand: 'right' as Hand,
    notes: ['F4', 'G4', 'A4', 'Bb4', 'C5', 'D5', 'E5', 'F5'],
    fingerings: [
      { note: 'F4', finger: 1, hand: 'right' },
      { note: 'G4', finger: 2, hand: 'right' },
      { note: 'A4', finger: 3, hand: 'right' },
      { note: 'Bb4', finger: 4, hand: 'right' },
      { note: 'C5', finger: 1, hand: 'right' },
      { note: 'D5', finger: 2, hand: 'right' },
      { note: 'E5', finger: 3, hand: 'right' },
      { note: 'F5', finger: 4, hand: 'right' },
    ],
    tips: [
      'Finger 4 on Bb is the critical moment. Keep the hand relaxed.',
      'Thumb passes under after A4 — slightly earlier than in C major.',
    ],
  },
  {
    id: 'bb-major-scale-rh',
    title: 'Bb Major Scale (RH)',
    description: 'Two flats (Bb and Eb). Closer to Chopin\'s preferred black-key topography. The hand naturally rises to the black keys.',
    category: ExerciseCategory.Technical,
    type: ExerciseType.Scale,
    difficulty: Difficulty.Intermediate,
    key: 'Bb Major',
    hand: 'right' as Hand,
    notes: ['Bb3', 'C4', 'D4', 'Eb4', 'F4', 'G4', 'A4', 'Bb4'],
    fingerings: [
      { note: 'Bb3', finger: 2, hand: 'right' },
      { note: 'C4', finger: 1, hand: 'right' },
      { note: 'D4', finger: 2, hand: 'right' },
      { note: 'Eb4', finger: 3, hand: 'right' },
      { note: 'F4', finger: 1, hand: 'right' },
      { note: 'G4', finger: 2, hand: 'right' },
      { note: 'A4', finger: 3, hand: 'right' },
      { note: 'Bb4', finger: 4, hand: 'right' },
    ],
    tips: [
      'Starts on finger 2, not finger 1. The thumb tucks under to C.',
      'Two thumb passes — after Bb3 and after Eb4. Both should be smooth.',
    ],
  },
  {
    id: 'a-minor-harmonic-rh',
    title: 'A Minor Harmonic Scale (RH)',
    description: 'The raised 7th (G#) creates an exotic interval. This is the scale behind most dramatic classical music — minor keys with a leading tone that pulls toward resolution.',
    category: ExerciseCategory.Technical,
    type: ExerciseType.Scale,
    difficulty: Difficulty.Intermediate,
    key: 'A Minor',
    hand: 'right' as Hand,
    notes: ['A3', 'B3', 'C4', 'D4', 'E4', 'F4', 'G#4', 'A4'],
    fingerings: [
      { note: 'A3', finger: 1, hand: 'right' },
      { note: 'B3', finger: 2, hand: 'right' },
      { note: 'C4', finger: 3, hand: 'right' },
      { note: 'D4', finger: 1, hand: 'right' },
      { note: 'E4', finger: 2, hand: 'right' },
      { note: 'F4', finger: 3, hand: 'right' },
      { note: 'G#4', finger: 4, hand: 'right' },
      { note: 'A4', finger: 5, hand: 'right' },
    ],
    tips: [
      'The augmented second (F to G#) is the signature sound. Let it ring.',
      'Chopin loved this scale — it appears throughout the Ballades and Nocturnes.',
    ],
  },
  {
    id: 'e-minor-harmonic-rh',
    title: 'E Minor Harmonic Scale (RH)',
    description: 'The relative minor of G major with a raised 7th (D#). A dark, expressive scale that appears in countless Chopin works.',
    category: ExerciseCategory.Technical,
    type: ExerciseType.Scale,
    difficulty: Difficulty.Intermediate,
    key: 'E Minor',
    hand: 'right' as Hand,
    notes: ['E4', 'F#4', 'G4', 'A4', 'B4', 'C5', 'D#5', 'E5'],
    fingerings: [
      { note: 'E4', finger: 1, hand: 'right' },
      { note: 'F#4', finger: 2, hand: 'right' },
      { note: 'G4', finger: 3, hand: 'right' },
      { note: 'A4', finger: 1, hand: 'right' },
      { note: 'B4', finger: 2, hand: 'right' },
      { note: 'C5', finger: 3, hand: 'right' },
      { note: 'D#5', finger: 4, hand: 'right' },
      { note: 'E5', finger: 5, hand: 'right' },
    ],
    tips: [
      'The D# pulls strongly toward E — feel that magnetic pull at the top.',
      'Compare with E minor natural (D instead of D#) to hear the difference.',
    ],
  },

  // --- Rhythm & Time ---
  {
    id: 'rhythm-quarter-half',
    title: 'Quarter and Half Notes',
    description: 'The foundation of musical time. Quarter notes get one beat, half notes get two, and the whole note at the end gets four. Listen to how the longer notes create breathing room between phrases.',
    category: ExerciseCategory.Rhythm,
    type: ExerciseType.Drill,
    difficulty: Difficulty.Beginner,
    key: 'C Major',
    hand: 'right' as Hand,
    notes: ['C4', 'D4', 'E4', 'F4', 'G4', 'A4', 'B4'],
    durations: [1, 1, 2, 1, 1, 2, 4],
    fingerings: [
      { note: 'C4', finger: 1, hand: 'right' },
      { note: 'D4', finger: 2, hand: 'right' },
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'F4', finger: 4, hand: 'right' },
      { note: 'G4', finger: 5, hand: 'right' },
      { note: 'A4', finger: 3, hand: 'right' },
      { note: 'B4', finger: 4, hand: 'right' },
    ],
    tips: [
      'Count aloud: "1, 2, 3-4, 1, 2, 3-4, 1-2-3-4." The half notes last twice as long as the quarters.',
      'Let the half and whole notes ring fully. Do not cut them short.',
      'This pattern teaches you to feel subdivisions of time, not just play notes.',
      'The short notes are the words; the long notes are the pauses where meaning settles. Music needs both.',
    ],
  },
  {
    id: 'rhythm-eighth-runs',
    title: 'Eighth Note Runs',
    description: 'Quick eighth notes develop speed and evenness. Eight fast notes climb the scale, then a half note lets the phrase land and breathe. Two notes per beat instead of one.',
    category: ExerciseCategory.Rhythm,
    type: ExerciseType.Drill,
    difficulty: Difficulty.Intermediate,
    key: 'C Major',
    hand: 'right' as Hand,
    notes: ['C4', 'D4', 'E4', 'F4', 'G4', 'A4', 'B4', 'C5', 'C5'],
    durations: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 2],
    fingerings: [
      { note: 'C4', finger: 1, hand: 'right' },
      { note: 'D4', finger: 2, hand: 'right' },
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'F4', finger: 1, hand: 'right' },
      { note: 'G4', finger: 2, hand: 'right' },
      { note: 'A4', finger: 3, hand: 'right' },
      { note: 'B4', finger: 4, hand: 'right' },
      { note: 'C5', finger: 5, hand: 'right' },
    ],
    tips: [
      'Count "1-and-2-and-3-and-4-and" for the eighth notes. Each syllable is one note.',
      'Evenness matters more than speed. Every eighth note should be exactly the same length.',
      'The landing half note at the end should feel like a relief, not a crash.',
      'Variation: try starting soft and growing louder through the run, then landing quietly. A crescendo run into a soft arrival is one of the most expressive gestures in piano music.',
    ],
  },
  {
    id: 'rhythm-dotted',
    title: 'Dotted Rhythm',
    description: 'The dotted quarter followed by an eighth note creates a long-short swing: "DA-da, DA-da." This pattern drives Baroque and Classical music forward. The dot adds half the note\'s value to itself.',
    category: ExerciseCategory.Rhythm,
    type: ExerciseType.Drill,
    difficulty: Difficulty.Intermediate,
    key: 'C Major',
    hand: 'right' as Hand,
    notes: ['C4', 'D4', 'E4', 'F4', 'G4', 'A4', 'G4', 'E4', 'C4'],
    durations: [1.5, 0.5, 1.5, 0.5, 1.5, 0.5, 1.5, 0.5, 2],
    fingerings: [
      { note: 'C4', finger: 1, hand: 'right' },
      { note: 'D4', finger: 2, hand: 'right' },
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'F4', finger: 4, hand: 'right' },
      { note: 'G4', finger: 5, hand: 'right' },
      { note: 'A4', finger: 3, hand: 'right' },
    ],
    tips: [
      'The long note (dotted quarter) lasts three times as long as the short note (eighth). Feel the asymmetry.',
      'Do not rush the short note. It should land precisely at the right moment, not early.',
      'This rhythm appears everywhere: marches, nocturnes, overtures. Master it and you unlock entire repertoires.',
    ],
  },
  {
    id: 'rhythm-triplets',
    title: 'Triplet Feel',
    description: 'Three notes per beat instead of two or four. Triplets create a flowing, waltz-like feel. Each group of three divides one beat into equal thirds. Think "1-trip-let, 2-trip-let."',
    category: ExerciseCategory.Rhythm,
    type: ExerciseType.Drill,
    difficulty: Difficulty.Advanced,
    key: 'C Major',
    hand: 'right' as Hand,
    notes: ['C4', 'E4', 'G4', 'E4', 'G4', 'C5', 'G4', 'E4', 'C4', 'C4'],
    durations: [0.333, 0.333, 0.333, 0.333, 0.333, 0.333, 0.333, 0.333, 0.333, 2],
    fingerings: [
      { note: 'C4', finger: 1, hand: 'right' },
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'G4', finger: 5, hand: 'right' },
      { note: 'C5', finger: 5, hand: 'right' },
    ],
    tips: [
      'Say "tri-po-let" for each group of three. All three syllables must be exactly equal.',
      'The common mistake is turning triplets into dotted rhythms (long-short). They are not the same.',
      'Chopin used triplets constantly, especially in nocturnes. The left hand often plays triplets while the right hand sings in duple time.',
      'Triplets flow like water. Duple rhythms march like soldiers. Learning to switch between them is learning to speak two dialects of the same language.',
    ],
  },

  // --- Finger Character (Chopin's principle: cultivate inequality) ---
  {
    id: 'finger-character-thumb',
    title: 'Thumb: The Anchor',
    description: 'Chopin rejected the idea of making all fingers equally strong. The thumb is naturally bold and grounding. Use its weight to anchor phrases, then let the lighter fingers dance above it.',
    category: ExerciseCategory.Musicality,
    type: ExerciseType.Drill,
    difficulty: Difficulty.Intermediate,
    key: 'C Major',
    hand: 'right' as Hand,
    notes: ['C4', 'E4', 'G4', 'C4', 'F4', 'A4', 'C4', 'G4', 'E4', 'C4'],
    fingerings: [
      { note: 'C4', finger: 1, hand: 'right' },
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'G4', finger: 5, hand: 'right' },
      { note: 'F4', finger: 4, hand: 'right' },
      { note: 'A4', finger: 5, hand: 'right' },
    ],
    tips: [
      'Accent the thumb notes (C4) slightly. They are the pillars; the other notes lean on them.',
      'The thumb provides the bass voice in a melody. Even in a single-line passage, it grounds the harmony.',
      'Why this matters: in Chopin\'s music, the thumb often carries a hidden inner voice while other fingers play the melody above.',
    ],
  },
  {
    id: 'finger-character-ring',
    title: 'Ring Finger: The Singer',
    description: 'Chopin called finger 4 the "Cinderella" — weakest by nature, but capable of the most tender, singing tone when cultivated. This exercise lets finger 4 carry the melody.',
    category: ExerciseCategory.Musicality,
    type: ExerciseType.Drill,
    difficulty: Difficulty.Intermediate,
    key: 'E Major',
    hand: 'right' as Hand,
    notes: ['G#4', 'A4', 'G#4', 'F#4', 'E4', 'F#4', 'G#4', 'A4', 'B4', 'A4', 'G#4'],
    fingerings: [
      { note: 'E4', finger: 1, hand: 'right' },
      { note: 'F#4', finger: 2, hand: 'right' },
      { note: 'G#4', finger: 3, hand: 'right' },
      { note: 'A4', finger: 4, hand: 'right' },
      { note: 'B4', finger: 5, hand: 'right' },
    ],
    tips: [
      'Let finger 4 (on A4) be the loudest note in each phrase. It carries the emotional peak.',
      'The weakness of finger 4 produces a naturally soft, singing quality. Do not fight it — use it.',
      'Variation: play the entire passage with finger 4 slightly louder than the rest. Then reverse: make finger 4 the quietest. Hear how the phrase changes character.',
      'Chopin: "The fourth finger is like a precious voice that must be carefully drawn out."',
    ],
  },
  {
    id: 'finger-character-pinky',
    title: 'Pinky: The Bright Edge',
    description: 'The pinky sits at the top of every phrase. It is the note the audience hears most clearly. Its job is not power but clarity and brightness.',
    category: ExerciseCategory.Musicality,
    type: ExerciseType.Drill,
    difficulty: Difficulty.Intermediate,
    key: 'C Major',
    hand: 'right' as Hand,
    notes: ['C4', 'D4', 'E4', 'F4', 'G4', 'F4', 'G4', 'E4', 'G4', 'D4', 'G4', 'C4'],
    fingerings: [
      { note: 'C4', finger: 1, hand: 'right' },
      { note: 'D4', finger: 2, hand: 'right' },
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'F4', finger: 4, hand: 'right' },
      { note: 'G4', finger: 5, hand: 'right' },
    ],
    tips: [
      'The G4 (finger 5) should ring clearly above the other notes. It is the soprano voice.',
      'Do not force the pinky. Tilt the hand slightly outward to let the pinky\'s natural weight project.',
      'In real music: the top note of a chord is always the one the ear follows. The pinky must learn to project without strain.',
      'Why this matters: in Chopin\'s Nocturnes, the melody is almost always in the top voice — your pinky.',
    ],
  },

  // --- Bach Fragments (Central to Chopin's curriculum) ---
  {
    id: 'bach-invention-1-rh',
    title: 'Bach Invention No. 1 (RH Fragment)',
    description: 'Chopin told every student: "Bach is the alpha and omega." This is the opening subject of the most famous Invention — a rising scale fragment that becomes a conversation between two voices. Learn this and you begin to hear polyphony.',
    category: ExerciseCategory.Musicality,
    type: ExerciseType.Etude,
    difficulty: Difficulty.Advanced,
    key: 'C Major',
    hand: 'right' as Hand,
    notes: ['C4', 'D4', 'E4', 'F4', 'D4', 'E4', 'C4', 'E4', 'G4', 'A4', 'F4', 'G4', 'E4', 'F4', 'D4', 'G4'],
    fingerings: [
      { note: 'C4', finger: 1, hand: 'right' },
      { note: 'D4', finger: 2, hand: 'right' },
      { note: 'E4', finger: 3, hand: 'right' },
      { note: 'F4', finger: 4, hand: 'right' },
      { note: 'G4', finger: 5, hand: 'right' },
      { note: 'A4', finger: 1, hand: 'right' },
    ],
    tips: [
      'This subject is a statement. It rises with purpose, steps back, then leaps forward. Shape it like a spoken declaration.',
      'Bach wrote this to teach independence of voices. Even this single-line fragment implies two conversations happening at once.',
      'Play it slowly enough to hear every note ring. Speed destroys the counterpoint that makes Bach worth playing.',
      'Chopin kept Bach\'s Well-Tempered Clavier on his piano at all times. This was not sentimental — it was pedagogical.',
    ],
  },
  {
    id: 'bach-invention-8-rh',
    title: 'Bach Invention No. 8 (RH Fragment)',
    description: 'A lyrical, singing subject in F major. Where Invention No. 1 is declarative, No. 8 is tender. Bach proves that counterpoint is not just intellectual; it can be deeply emotional.',
    category: ExerciseCategory.Musicality,
    type: ExerciseType.Etude,
    difficulty: Difficulty.Advanced,
    key: 'F Major',
    hand: 'right' as Hand,
    notes: ['F4', 'A4', 'C5', 'A4', 'F4', 'C5', 'A4', 'F4', 'A4', 'G4', 'F4', 'E4', 'F4'],
    fingerings: [
      { note: 'F4', finger: 1, hand: 'right' },
      { note: 'A4', finger: 3, hand: 'right' },
      { note: 'C5', finger: 5, hand: 'right' },
      { note: 'G4', finger: 2, hand: 'right' },
      { note: 'E4', finger: 1, hand: 'right' },
    ],
    tips: [
      'This subject sings. Let it breathe between the arpeggiated leaps and the stepwise descent.',
      'The descent at the end (A-G-F-E-F) is a sigh. Play it that way — slightly softer, slightly slower.',
      'Variation: once you know the notes, try shaping the whole phrase in one breath — crescendo to the high C5, then diminuendo to the final F4.',
      'Why this matters: Chopin\'s own melodic style grew directly from Bach. Hear this and you hear the roots of the Nocturnes.',
    ],
  },

  // --- Performance ---
  {
    id: 'visualization',
    title: 'Mental Practice',
    description: 'Close your eyes. Visualize playing the B Major five-finger pattern without touching the piano. Hear each note clearly. Feel the keys under your fingers.',
    category: ExerciseCategory.Performance,
    type: ExerciseType.Mental,
    difficulty: Difficulty.Advanced,
    key: 'N/A',
    hand: 'both' as Hand,
    notes: [],
    fingerings: [],
    tips: [
      'If you cannot hear it clearly in your mind, you don\'t know it yet.',
      'Visualize the sensation of the black keys under fingers 2, 3, 4.',
      'This is how concert pianists practice on airplanes.',
      'Why this matters: the goal of practice is not stronger fingers. It is a clearer internal model of the music. When the inner hearing is vivid, the fingers follow.',
    ],
  },
];
